name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Inject API key
      run: |
        echo "Injecting API key into HTML file"
        sed -i 's/REPLACE_WITH_API_KEY/${{ secrets.YOUTUBE_API_KEY }}/g' index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
