name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Inject API keys
      run: |
        echo "Injecting API keys into HTML file"
        sed -i 's/FB_KEY/${{ secrets.FB_KEY }}/g' public/index.html
        sed -i 's/YOUTUBE_KEY/${{ secrets.YOUTUBE_KEY }}/g' public/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
